config/routes.rb
Football::Application.routes.draw do
  get "leagues/select" => "leagues#select", :as => "leagues_select"
  put "leagues/pick_league" => "leagues#pick_league", :as => "league_pick_league"
  
  
  resources :comments
  resources :memberships
  resources :picks
  resources :matchups
  resources :leagues
  resources :profiles
  devise_for :users
  
  get "tools" => "admin#tools", :as => "admin_tools"
  root :to => "profiles#show"
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :profile
  belongs_to :league
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :need_profile!
  before_filter :need_league!, :except => [:new, :create]
  
  # GET /memberships
  # GET /memberships.xml
  def index
    @memberships = Membership.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.xml
  def show
    @membership = Membership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @membership }
    end
  end

  # GET /memberships/new
  # GET /memberships/new.xml
  def new
    @membership = Membership.new
    @leagues = League.all - current_user.profile.leagues
    if @leagues.empty?
      flash[:notice] = "There are currently no Leagues to Join."
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    @membership = Membership.find(params[:id])
  end

  # POST /memberships
  # POST /memberships.xml
  def create
    @membership = Membership.new(params[:membership])
    @membership.profile_id = current_user.profile.id
    @membership.num_of_picks = params[:num_of_picks]

    respond_to do |format|
      if @membership.save
        format.html { redirect_to(@membership, :notice => 'Membership was successfully created.') }
        format.xml  { render :xml => @membership, :status => :created, :location => @membership }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @membership.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.xml
  def update
    @membership = Membership.find(params[:id])
    @membership.num_of_picks = params[:num_of_picks]
    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        format.html { redirect_to(@membership, :notice => 'Membership was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @membership.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.xml
  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to(memberships_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :league_id %><br />
    <%= league = collection_select(:membership, :league_id, League.all, :id, :name) %>
  </div>
  <div class="field">
    Number of Picks to Purchase<br />
    <%= f.text_field :num_of_picks %>
  </div>
  <div class="field">
    <%= f.label :paid %><br />
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :league_id %><br />
    <b><%= League.find_by_id(@membership.league_id).name %></b>
  </div>
  <div class="field">
    <%= f.label :profile_id %><br />
    <b><%= Profile.find_by_id(@membership.profile_id).full_name %></b>
  </div>
  <div class="field">
    Number of Picks to Purchase<br />
    <%= select_tag(:num_of_picks, options_for_select(1..16)) %><br />
  </div>
<% if admin?(current_league) %>
  <div class="field">
    <%= f.label :paid %><br />
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing memberships for <%= current_league.name %></h1>

<table>
  <tr>
    <th>Member</th>
    <th>Picks</th>
    <th>Paid</th>
    <th>Admin</th>
    <th></th>
<% if admin?(current_league) %>
    <th></th>
    <th></th>
<% end %>
  </tr>

<% current_league.memberships.each do |membership| %>
  <tr>
    <td><%= Profile.find_by_id(membership.profile_id).full_name %></td>
    <td><%= membership.num_of_picks %></td>
    <td><%= membership.paid %></td>
    <td><%= membership.admin %></td>
    <td><%= link_to 'Show', membership %></td>
<% if admin?(current_league) %>    
    <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
    <td><%= link_to 'Destroy', membership, :confirm => 'Are you sure?', :method => :delete %></td>
<% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Join League', new_membership_path %>

app/views/memberships/new.html.erb
<h1>Join A League</h1>

<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% unless @leagues.empty? %>

  <div class="field">
    <%= f.label :league_id %><br />
    <%= league = collection_select(:membership, :league_id, @leagues, :id, :name) %>
  </div>
  
  <div class="field">
    Number of Picks to Purchase<br />
    <%= select_tag(:num_of_picks, options_for_select(1..16)) %><br />
  </div>
<% if admin?(current_league) %>
  <div class="field">
    <%= f.label :paid %><br />
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% end %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p>
  <b>League:</b>
  <%= League.find_by_id(@membership.league_id).name %>
</p>

<p>
  <b>Member:</b>
  <%= Profile.find_by_id(@membership.profile_id).full_name %>
</p>

<p>
  <b>Num of picks:</b>
  <%= @membership.num_of_picks %>
</p>

<p>
  <b>Paid:</b>
  <%= @membership.paid %>
</p>

<p>
  <b>Admin:</b>
  <%= @membership.admin %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>