config/routes.rb
Football::Application.routes.draw do
  get "leagues/select" => "leagues#select", :as => "leagues_select"
  put "leagues/pick_league" => "leagues#pick_league", :as => "league_pick_league"
  
  
  resources :comments
  resources :memberships
  resources :picks
  resources :matchups
  resources :leagues
  resources :profiles
  devise_for :users
  
  get "tools" => "admin#tools", :as => "admin_tools"
  root :to => "profiles#show"
end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :profiles, :through => :memberships
  has_many :picks
  
  def admins
    admins = Array.new
    self.memberships.each do |membership|
      if membership.admin
        admins << membership.profile
      end
    end
    return admins
  end
  
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_filter :authenticate_user!
  # GET /leagues
  # GET /leagues.xml
  def index
    @leagues = League.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @leagues }
    end
  end

  # GET /leagues/1
  # GET /leagues/1.xml
  def show
    @league = League.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @league }
    end
  end

  # GET /leagues/new
  # GET /leagues/new.xml
  def new
    @league = League.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @league }
    end
  end

  # GET /leagues/1/edit
  def edit
    @league = League.find(params[:id])
  end

  # POST /leagues
  # POST /leagues.xml
  def create
    @league = League.new(params[:league])
    @league.profiles << current_user.profile

    respond_to do |format|
      if @league.save
        membership = Membership.find_by_league_id_and_profile_id(@league.id, current_user.profile.id)
        membership.admin = true
        membership.num_of_picks = 0
        membership.save
        format.html { redirect_to(@league, :notice => 'League was successfully created.') }
        format.xml  { render :xml => @league, :status => :created, :location => @league }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @league.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /leagues/1
  # PUT /leagues/1.xml
  def update
    @league = League.find(params[:id])

    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to(@league, :notice => 'League was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @league.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.xml
  def destroy
    @league = League.find(params[:id])
    @league.destroy

    respond_to do |format|
      format.html { redirect_to(leagues_url) }
      format.xml  { head :ok }
    end
  end
  
  def select
    respond_to do |format|
      format.html # index.html.erb
      format.xml
    end
  end
  
  def pick_league
    puts "THIS IS GETTING RUN"
    set_current_league(params[:league_select])
    redirect_to(:back)
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    Name Of The League<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
   Give your members the ability to repick a team from week to week:<br />
    <%= f.check_box :repick %> <%= f.label :repick %>
  </div>
  <div class="field">
    Make status of payment public:<br />
    <%= f.check_box :show_paid %> <%= f.label :show_paid %>
  </div>
  <div class="field">
    Make member pick history public:<br />
    <%= f.check_box :show_history %> <%= f.label :show_history %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<h1>Listing leagues</h1>

<table>

  <tr>
    <th>League Name</th>
    <th>Repick</th>
    <th>Show Paid</th>
    <th>Show History</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leagues.each do |league| %>
  <tr>
    <td><%= league.name %></td>
    <td><%= league.repick %></td>
    <td><%= league.show_paid %></td>
    <td><%= league.show_history %></td>
    <td><%= link_to 'Show', league %></td>
    <% if admin?(league) %>
    <td><%= link_to 'Edit', edit_league_path(league) %></td>
    <td><%= link_to 'Destroy', league, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p>
  <b>Name:</b>
  <%= @league.name %>
</p>

<p>
  <b>Repick:</b>
  <%= @league.repick %>
</p>

<p>
  <b>Show Paid:</b>
  <%= @league.show_paid %>
</p>

<p>
  <b>Show History:</b>
  <%= @league.show_history %>
</p>

<p>
  <b>League Admins:</b><br/>
  <% unless @league.admins.nil? %>
    <% for profile in @league.admins %>
        <%= profile.first %> <%= profile.last %><br/>
    <% end %>
    
  <% end %>
</p>
  

<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>