config/routes.rb
Football::Application.routes.draw do
  get "leagues/select" => "leagues#select", :as => "leagues_select"
  put "leagues/pick_league" => "leagues#pick_league", :as => "league_pick_league"
  
  
  resources :comments
  resources :memberships
  resources :picks
  resources :matchups
  resources :leagues
  resources :profiles
  devise_for :users
  
  get "tools" => "admin#tools", :as => "admin_tools"
  root :to => "profiles#show"
end

app/models/matchup.rb
class Matchup < ActiveRecord::Base
end

app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /matchups
  # GET /matchups.xml
  def index
    # Should be Current_Week
    @week_num = params[:week_num] ? params[:week_num] : 1
    @matchups = Matchup.find_all_by_week(@week_num).sort_by { |matchup| [ matchup.time, matchup.away ] }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @matchups }
    end
  end

  # GET /matchups/1
  # GET /matchups/1.xml
  def show
    @matchup = Matchup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @matchup }
    end
  end

  # GET /matchups/new
  # GET /matchups/new.xml
  def new
    @matchup = Matchup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @matchup }
    end
  end

  # GET /matchups/1/edit
  def edit
    @matchup = Matchup.find(params[:id])
    @winner = params[:winner]
    if @winner
      @selected_winner = Team.find_by_id(@winner)
    end
    @teams = [Team.find_by_id(@matchup.away), Team.find_by_id(@matchup.home)]
  end

  # POST /matchups
  # POST /matchups.xml
  def create
    @matchup = Matchup.new(params[:matchup])

    respond_to do |format|
      if @matchup.save
        format.html { redirect_to(@matchup, :notice => 'Matchup was successfully created.') }
        format.xml  { render :xml => @matchup, :status => :created, :location => @matchup }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @matchup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /matchups/1
  # PUT /matchups/1.xml
  def update
    @matchup = Matchup.find(params[:id])
    if params[:winner]
      @matchup.winner = params[:winner]
    end

    respond_to do |format|
      if @matchup.update_attributes(params[:matchup])
        format.html { redirect_to(:action => "index", :week_num => @matchup.week, :notice => 'Matchup was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @matchup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /matchups/1
  # DELETE /matchups/1.xml
  def destroy
    @matchup = Matchup.find(params[:id])
    @matchup.destroy

    respond_to do |format|
      format.html { redirect_to(matchups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/matchups_helper.rb
module MatchupsHelper
  def getFullName(id)
    @team = Team.find_by_id(id)
    if @team
      @team.full_name
    end
  end
  
  def selectWinner(id)
    redirect_to :action => "edit", :winner => id
  end
end

app/views/matchups/_form.html.erb
<%= form_for(@matchup) do |f| %>
  <% if @matchup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matchup.errors.count, "error") %> prohibited this matchup from being saved:</h2>

      <ul>
      <% @matchup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home %><br />
    <%= f.text_field :home %>
  </div>
  <div class="field">
    <%= f.label :away %><br />
    <%= f.text_field :away %>
  </div>
  <div class="field">
    <%= f.label :week %><br />
    <%= f.text_field :week %>
  </div>
  <div class="field">
    <%= f.label :winner %><br />
    <%= f.text_field :winner %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matchups/_weeks.html.erb
Weeks <br />

<%= link_to "1", :controller => "matchups", :action => "index", :week_num => 1 %> | 
<%= link_to "2", :controller => "matchups", :action => "index", :week_num => 2 %> | 
<%= link_to "3", :controller => "matchups", :action => "index", :week_num => 3 %> | 
<%= link_to "4", :controller => "matchups", :action => "index", :week_num => 4 %> | 
<%= link_to "5", :controller => "matchups", :action => "index", :week_num => 5 %> | 
<%= link_to "6", :controller => "matchups", :action => "index", :week_num => 6 %> | 
<%= link_to "7", :controller => "matchups", :action => "index", :week_num => 7 %> | 
<%= link_to "8", :controller => "matchups", :action => "index", :week_num => 8 %> | 
<%= link_to "9", :controller => "matchups", :action => "index", :week_num => 9 %> | 
<%= link_to "10", :controller => "matchups", :action => "index", :week_num => 10 %> | 
<%= link_to "11", :controller => "matchups", :action => "index", :week_num => 11 %> | 
<%= link_to "12", :controller => "matchups", :action => "index", :week_num => 12 %> | 
<%= link_to "13", :controller => "matchups", :action => "index", :week_num => 13 %> | 
<%= link_to "14", :controller => "matchups", :action => "index", :week_num => 14 %> | 
<%= link_to "15", :controller => "matchups", :action => "index", :week_num => 15 %> | 
<%= link_to "16", :controller => "matchups", :action => "index", :week_num => 16 %> | 
<%= link_to "17", :controller => "matchups", :action => "index", :week_num => 17 %>

app/views/matchups/edit.html.erb
<h1>Select Winner</h1>

<%= form_for(@matchup) do |f| %>
  <% if @matchup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matchup.errors.count, "error") %> prohibited this matchup from being saved:</h2>

      <ul>
      <% @matchup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <h2>Matchup: 
  <%= getFullName(@matchup.away) %> @ <%= getFullName(@matchup.home) %></h2>

  <div class="field">
    <h3>Select Winner</h3>

    <% if @selected_winner %>
    <select name='winner'>
      <%= options_from_collection_for_select(@teams, "id", :full_name, @selected_winner.id) %>
    </select>
    <% else %>
      <%= collection_select(:matchup, :winner, @teams, :id, :full_name)%>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @matchup %> |
<%= link_to 'Back', :controller => "matchups", :action => "index", :week_num => @matchup.week %>

app/views/matchups/index.html.erb
<h1>Listing matchups for Week <%= @week_num %></h1>

<%= render "weeks" %>

<table>
  <tr>
    <th>Matchup</th>
    <th>Winner</th>
    <th>Time</th>
    <th></th>
    <th></th>
  </tr>

<% @matchups.each do |matchup| %>
  <tr>
    <td><%= link_to getFullName(matchup.away), :controller => "matchups", :action => "edit", :id => matchup.id, :winner => matchup.away %> @ 
    <%= link_to getFullName(matchup.home), :controller => "matchups", :action => "edit", :id => matchup.id, :winner => matchup.home %></td>
    
        <% if Team.find_by_id(matchup.winner)%>
    <td><%= getFullName(matchup.winner) %></td>
        <% else %>
        <td>TBD</td>
        <% end %>
        
    <td><%= matchup.time.to_formatted_s(:short) %> TBD </td>
    <td><%= link_to 'Show', matchup %></td>
    <td><%= link_to 'Edit', edit_matchup_path(matchup) %></td>
  </tr>
<% end %>
</table>

app/views/matchups/new.html.erb
<h1>New matchup</h1>

<%= render 'form' %>

<%= link_to 'Back', matchups_path %>

app/views/matchups/show.html.erb
<p>
  <b>Home:</b>
  <%= getFullName(@matchup.home) %>
</p>

<p>
  <b>Away:</b>
  <%= getFullName(@matchup.away) %>
</p>

<p>
  <b>Week:</b>
  <%= @matchup.week %>
</p>

<p>
  <b>Winner:</b>
  <%= getFullName(@matchup.winner) %>
</p>

<p>
  <b>Time:</b>
  <%= @matchup.time %>
</p>


<%= link_to 'Edit', edit_matchup_path(@matchup) %> |
<%= link_to 'Back', :controller => "matchups", :action => "index", :week_num => @matchup.week %>