config/routes.rb
Football::Application.routes.draw do
  get "leagues/select" => "leagues#select", :as => "leagues_select"
  put "leagues/pick_league" => "leagues#pick_league", :as => "league_pick_league"
  
  
  resources :comments
  resources :memberships
  resources :picks
  resources :matchups
  resources :leagues
  resources :profiles
  devise_for :users
  
  get "tools" => "admin#tools", :as => "admin_tools"
  root :to => "profiles#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Football</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
	
	<div id="user_nav">
	  <% if user_signed_in? %>
	    <% if has_profile? %>
        Hello, <%= current_user.profile.first %>.  <%= link_to 'Edit My Profile', edit_profile_path(current_user.profile) %>
        <br />
	    Signed in as <%= current_user.email %>. Not you?
	    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	    <br />
      <% if current_league %>
        <%= form_for current_league, :url => {:controller => "leagues", :action => "pick_league"} do |f| %>
          League:
          <select name='league_select'>
            <%= options_from_collection_for_select(current_user.profile.leagues, "id", :name, current_league.id) %>
          </select>
          <%= submit_tag "Go" %>
        <% end %>
      <% else %>
        <%= link_to 'Join League', new_membership_path %> 
      <% end %>
	    <% end %>
	  <% else %>
	    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
	  <% end %>
	</div>
	
	-------------------------------
	
	<div id="tabs">
    <%= link_to "Profiles", profiles_path %>
    <%= link_to "Make Picks", picks_path %>
    <%= link_to "Admin Tools", admin_tools_path %>
	</div>

  -------------------------------
  <p id="notice"><%= notice %></p>
	<p id="alert"><%= alert %></p>

  
</head>
<body>
<%= yield %>

</body>
</html>
  